default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: p@ssw0rd013459
  timeout: 5000
  host: localhost
  port: 5432


development:
  <<: *default
  database: bookstore_dev
test:
  <<: *default
  database: bookstore_dev

production:
  <<: *default
  database: bookstore_dev